# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.TextField()),
                ('number_of_tracks', models.IntegerField(default=1)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('mins_fw_acc', models.IntegerField()),
                ('mins_fw_brk', models.IntegerField()),
                ('mins_rev_acc', models.IntegerField()),
                ('mins_rev_brk', models.IntegerField()),
                ('mins_main', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='switch',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutu.Track'),
        ),
    ]
