# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='mins_fw_acc',
            new_name='mins_acc',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='mins_fw_brk',
            new_name='mins_brk',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='mins_rev_acc',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='mins_rev_brk',
        ),
    ]
