# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0002_auto_20170722_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.TextField(default='Старт-Финиш'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='position',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
        ),
    ]
