# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0004_switch_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='capacity',
            new_name='lanes',
        ),
    ]
