# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0005_auto_20170723_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['position']},
        ),
    ]
