# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0006_auto_20170723_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['position'], 'verbose_name_plural': 'switches'},
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='lanes',
            new_name='trains_fit',
        ),
    ]
