# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0007_auto_20170723_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='start_name',
            field=models.TextField(default='Старт'),
        ),
    ]
