# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0008_track_start_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='length',
        ),
    ]
