# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0009_remove_track_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='simulation_filename',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='simulation_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
