# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0010_auto_20170723_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='last_simulation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
