# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0011_track_last_simulation_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='last_simulation_date_time',
            new_name='simulation_date_time',
        ),
    ]
