# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0013_track_simulation_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='simulation_progress',
            field=models.IntegerField(default=0),
        ),
    ]
