# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0014_auto_20170724_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='mins_main',
            new_name='mins_main_fw',
        ),
        migrations.AddField(
            model_name='switch',
            name='mins_main_bk',
            field=models.IntegerField(default=1),
        ),
    ]
