# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0015_auto_20170906_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='density_netto',
            field=models.FloatField(default=10.5),
        ),
        migrations.AddField(
            model_name='track',
            name='number_of_cargo_trains',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='track',
            name='number_of_passenger_trains',
            field=models.FloatField(default=3),
        ),
    ]
