# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0016_auto_20170906_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='mins_station',
            field=models.IntegerField(default=1),
        ),
    ]
